### ISSUE TITLE
聽得是否改為但聞

### ISSUE THREAD

**Issue by akira-cn** [GLanguage/jiaohu-wy#1]
聽得「甲」之事乃行「乙」之術

但聞「甲」之事乃行「乙」之術

**Comment by GLanguage** [comment]
Good suggestion! `但聞` 会被设为一个宏（我懒得把例子和README都改掉）

**Comment by GLanguage** [comment]
`但聞「甲」之事乃行「乙」之術` is added. Closing now. If you have any other suggestions, feel free to reopen it.
